### ISSUE TITLE
New Nutanix Cloud error in network perf test

### ISSUE THREAD

**Issue by paigerube14** [cloud-bulldozer/e2e-benchmarking#446] opened 2022-07-14 16:30 UTC
Trying to run network-perf test on the new nutanix cloud type fails with the below error. Need to make the labeling more robust for all cloud types to properly work 

```
% oc get nodes -l node-role.kubernetes.io/workload!=,node-role.kubernetes.io/infra!=,node-role.kubernetes.io/worker -o go-template='{{ range .items }}{{ index .metadata.labels "topology.kubernetes.io/zone" }}{{ "\n" }}{{ end }}' --kubeconfig config
<no value>
<no value>
```

```
07-14 11:17:45.364  [1mThu Jul 14 15:17:44 UTC 2022 Colocating uperf pods in different AZs[0m
07-14 11:17:45.364  Error from server (BadRequest): Unable to find "/v1, Resource=nodes" that match label selector "node-role.kubernetes.io/worker,node-role.kubernetes.io/workload!=,node-role.kubernetes.io/infra!=,topology.kubernetes.io/zone=<no", field selector "": unable to parse requirement: found '<', expected: identifier
07-14 11:17:46.055  Error from server (BadRequest): Unable to find "/v1, Resource=nodes" that match label selector "node-role.kubernetes.io/worker,node-role.kubernetes.io/workload!=,node-role.kubernetes.io/infra!=,topology.kubernetes.io/zone=value>", field selector "": found '>', expected: ',' or 'end of string'
```

The problem seems to be there are no "zones" in nutanix, see below node describe yaml

```
Name:               prubenda-*
Roles:              worker
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=prubenda-*
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/worker=
                    node.openshift.io/os_id=rhcos
Annotations:        machine.openshift.io/machine: openshift-machine-api/prubenda-*
                    machineconfiguration.openshift.io/controlPlaneTopology: HighlyAvailable
                    machineconfiguration.openshift.io/currentConfig: rendered-worker-*
                    machineconfiguration.openshift.io/desiredConfig: rendered-worker-*
                    machineconfiguration.openshift.io/desiredDrain: uncordon-rendered-worker-*
                    machineconfiguration.openshift.io/lastAppliedDrain: uncordon-rendered-worker-*
                    machineconfiguration.openshift.io/reason: 
                    machineconfiguration.openshift.io/state: Done
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Thu, 14 Jul 2022 09:42:03 -0400
Taints:             <none>
Unschedulable:      false
```

**Comment by paigerube14** [comment] 2022-07-14 18:01
@afcollins yes returns worker nodes properly

% oc get nodes -l node-role.kubernetes.io/workload!=,node-role.kubernetes.io/infra!=,node-role.kubernetes.io/worker | uniq
NAME                             STATUS   ROLES    AGE     VERSION
prubenda-11-pps2g-worker-5fqv6   Ready    worker   4h19m   v1.24.0+9546431
prubenda-11-pps2g-worker-7fbwr   Ready    worker   4h19m   v1.24.0+9546431

**Comment by afcollins** [comment] 2022-07-14 18:02
Okay, thank you for confirming.

Looks like all the code in question will be removed with: https://github.com/cloud-bulldozer/e2e-benchmarking/pull/444

**Comment by rsevilla87** [comment] 2022-08-03 08:36
Hey @paigerube14 , now that #444 has been merged, can you verify that you don't hit this issue anymore?

**Comment by wolfganghuse** [comment] 2022-08-03 10:06
@rsevilla87 just checked in a fresh deployed cluster... no Labels needed anymore

**Comment by jtaleric** [comment] 2022-08-03 15:57
Hey @paigerube14 feel free to reopen but it seems @wolfganghuse has confirmed that #444 has fixed this issue.

**Closed by jtaleric** 2022-08-03 15:57 UTC
